# # Use an official Node.js runtime as a parent image
# FROM node:18-alpine

# # Set the working directory in the container3
# WORKDIR /app

# # Copy package.json and package-lock.json to the working directory
# COPY package*.json ./

# # Install app dependencies
# RUN npm install

# # Copy the rest of your application code to the working directory
# COPY . .

# # Expose a port to communicate with the React app
# EXPOSE 5173

# # Start your React app
# CMD ["npm", "run", "dev"]
# Usa una imagen de Node.js oficial como base para la construcción
FROM node:18-alpine AS builder

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia package.json y package-lock.json al directorio de trabajo
COPY package*.json ./

# Instala las dependencias de la aplicación
RUN npm install

# Copia el resto del código de la aplicación al directorio de trabajo
COPY . .

# Construye la aplicación
RUN npm run build

# Usa una imagen de nginx para servir los archivos construidos
FROM nginx:alpine

# Copia los archivos construidos desde el contenedor de construcción al contenedor de nginx
COPY --from=builder /app/dist /usr/share/nginx/html

# Expone el puerto en el que nginx escuchará
EXPOSE 80

# Comando por defecto para ejecutar nginx
CMD ["nginx", "-g", "daemon off;"]