version: "1"
name: "ecommerce"
services:
  postgres:
    build: ./BACKEND/DB
    ports:
      - "33065:5432"
    environment:
      DB_HOST: postgres
      DB_USER: ecomers_user
      DB_PASS: ecomers_password
      # MYSQL_ROOT_PASSWORD: root_password
      # MYSQL_USER: blog_user
      # MYSQL_PASSWORD: blog_password
      # MYSQL_DATABASE: blog_zelda
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
  api:
    build: ./BACKEND/api
    ports:
      - "3005:4000"
    depends_on:
      - postgres
  frontend:
    build: ./FRONTEND
    ports:
      - "8000:5173"
    depends_on:
      - api
      - postgres

volumes:
  postgres-data:
    driver: local
