version: "2.3"
services:
  postgres:
    build: ./BACKEND/DB
    ports:
      - "33065:5432"
    environment:
      DB_HOST: postgres
      DB_USER: ecomers_user
      DB_PASS: ecomers_password
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
  api:
    build: ./BACKEND/api
    ports:
      - "3005:4000"
    depends_on:
      - postgres
    volumes:
      - "uploads:/app/uploads"
  frontend:
    build: ./FRONTEND
    ports:
      - "8000:5173"
    environment:
      VITE_APIPORT: "https://api.picolin.online/graphql"
      VITE_APIPORT_IMAGE: "https://api.picolin.online/"
      VITE_APIPORT_CATEGORY: "https://api.picolin.online/addCategory"
      VITE_APIPORT_PRODUCT: "https://api.picolin.online/addProduct"
      VITE_APIPORT_EDIT_CATEGORY: "https://api.picolin.online/editCategory"
      VITE_APIPORT_EDIT_PRODUCT: "https://api.picolin.online/editProduct"
    depends_on:
      - api
      - postgres

volumes:
  postgres-data:
    driver: local
  uploads:
    driver: local
