name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install frontend dependencies
      run: npm install
      working-directory: Proyecto/FRONTEND

    - name: Create jest.setupEnv.js
      run: |
        echo "import dotenv from 'dotenv';" > Proyecto/FRONTEND/src/tests/jest.setupEnv.js
        echo "dotenv.config();" >> Proyecto/FRONTEND/src/tests/jest.setupEnv.js
        echo "process.env.VITE_APIPORT = process.env.VITE_APIPORT || '${{ secrets.VITE_APIPORT }}';" >> Proyecto/FRONTEND/src/tests/jest.setupEnv.js
        echo "process.env.VITE_APIPORT_IMAGE = process.env.VITE_APIPORT_IMAGE || '${{ secrets.VITE_APIPORT_IMAGE }}';" >> Proyecto/FRONTEND/src/tests/jest.setupEnv.js
        echo "process.env.VITE_APIPORT_CATEGORY = process.env.VITE_APIPORT_CATEGORY || '${{ secrets.VITE_APIPORT_CATEGORY }}';" >> Proyecto/FRONTEND/src/tests/jest.setupEnv.js
        echo "process.env.VITE_APIPORT_PRODUCT = process.env.VITE_APIPORT_PRODUCT || '${{ secrets.VITE_APIPORT_PRODUCT }}';" >> Proyecto/FRONTEND/src/tests/jest.setupEnv.js

    - name: Run frontend tests
      run: npx jest 
      working-directory: Proyecto/FRONTEND

    - name: Build frontend project
      run: npm run build
      working-directory: Proyecto/FRONTEND
