name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install frontend dependencies
      run: npm install
      working-directory: Proyecto/FRONTEND

    - name: Set up environment variables
      run: |
        echo "VITE_APIPORT=${{ secrets.VITE_APIPORT }}" >> $GITHUB_ENV
        echo "VITE_APIPORT_IMAGE=${{ secrets.VITE_APIPORT_IMAGE }}" >> $GITHUB_ENV
        echo "VITE_APIPORT_CATEGORY=${{ secrets.VITE_APIPORT_CATEGORY }}" >> $GITHUB_ENV
        echo "VITE_APIPORT_PRODUCT=${{ secrets.VITE_APIPORT_PRODUCT }}" >> $GITHUB_ENV


    - name: Run frontend tests
      run: npx jest 
      working-directory: Proyecto/FRONTEND

    - name: Build frontend project
      run: npm run build
      working-directory: Proyecto/FRONTEND
