name: Deploy to Docker Server

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

      # Acceso al servidor
    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

      
      # Deploy
    - name: Deploy to Docker Server
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          docker stop $(docker ps -q)
          docker rm $(docker ps -a -q)
          docker rmi $(docker images -q)
          cd /var/www/html/picolin/Proyecto-software/Proyecto
          docker-compose up --build -d
        EOF
