name: Deploy to Docker Server

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }} 

    - name: Deploy to Docker Server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
        
          docker stop $(docker ps -q)
          
          docker rm $(docker ps -a -q)

          docker rmi $(docker images -q)

          cd /var/www/html/picolin/Proyecto-software/Proyecto

          docker-compose up --build

        EOF
